name: Continuous Integration

on:
  push:
    branches:
      - master
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
          cache-dependency-path: blog/package-lock.json

      - name: Install dependencies
        run: |
          cd blog
          npm ci

      - name: Run linter
        run: |
          cd blog
          npm run lint

      - name: Build app
        run: |
          cd blog
          npm run build
          echo "✅ Build terminé"
          ls -la dist/ || echo "❌ Répertoire dist manquant"

      # Vérifier que le build est valide avant upload
      - name: Verify build
        run: |
          cd blog
          if [ ! -d "dist" ]; then
            echo "❌ Erreur: Répertoire dist manquant"
            exit 1
          fi
          if [ ! -f "dist/index.html" ]; then
            echo "❌ Erreur: index.html manquant"
            exit 1
          fi
          echo "✅ Build valide"
          du -sh dist/

      # Upload artefact avec nom unique par version Node
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build-${{ github.run_number }}
          path: blog/dist/
          if-no-files-found: warn