name: Test React App

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  test:
    # S'exécute uniquement si le CI s'est terminé (succès OU échec)
    if: ${{ github.event.workflow_run.conclusion != 'cancelled' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
          cache-dependency-path: blog/package-lock.json

      - name: Install dependencies
        run: |
          cd blog
          npm ci

      # Vérifier que le CI a bien créé un artefact
      - name: Check CI status and artifacts
        run: |
          echo "🔍 Workflow CI info:"
          echo "Run ID: ${{ github.event.workflow_run.id }}"
          echo "Run Number: ${{ github.event.workflow_run.run_number }}"
          echo "Conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Status: ${{ github.event.workflow_run.status }}"
          echo "Head SHA: ${{ github.event.workflow_run.head_sha }}"
          echo "📦 Artefact attendu: react-build-${{ github.event.workflow_run.run_number }}"
          
          # Si le CI a échoué, on le signale
          if [ "${{ github.event.workflow_run.conclusion }}" != "success" ]; then
            echo "⚠️ ATTENTION: Le workflow CI n'a pas réussi (${{ github.event.workflow_run.conclusion }})"
            echo "Le fallback sera utilisé pour construire l'application"
          fi

      # Télécharger l'artefact build du CI
      - name: Download build artifact
        uses: actions/download-artifact@v4
        id: download-artifact
        continue-on-error: true
        with:
          name: react-build-${{ github.event.workflow_run.run_number }}
          path: ./dist

      # Si l'artefact n'existe pas, construire nous-mêmes
      - name: Build app (fallback if artifact missing)
        if: steps.download-artifact.outcome == 'failure'
        run: |
          echo "⚠️ Artefact manquant, construction en fallback..."
          cd blog
          npm run build
          cp -r dist ../dist/
          echo "✅ Build de fallback terminé"

      # Vérifier que le build existe et contient les fichiers attendus
      - name: Verify build
        run: |
          echo "Contenu du répertoire dist:"
          ls -la ./dist/
          echo "Vérification que index.html existe:"
          test -f ./dist/index.html && echo "✅ index.html trouvé" || echo "❌ index.html manquant"
          echo "Vérification de la taille du build:"
          du -sh ./dist/
          
      # Test de preview du build
      - name: Test build preview
        run: |
          cd blog
          npm run preview &
          sleep 5
          curl -f http://localhost:4173 || echo "⚠️ Preview test failed"
          pkill -f "vite preview" || true