name: Test React App

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  test:
    # S'exécute uniquement si le CI a réussi
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x, 21.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: blog/package-lock.json

      - name: Install dependencies
        run: |
          cd blog
          npm ci

      # Télécharger l'artefact build
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build-${{ github.event.workflow_run.run_number }}
          path: ./dist

      # Vérifier que le build existe et contient les fichiers attendus
      - name: Verify build
        run: |
          echo "Contenu du répertoire dist:"
          ls -la ./dist/
          echo "Vérification que index.html existe:"
          test -f ./dist/index.html && echo "✅ index.html trouvé" || echo "❌ index.html manquant"
          echo "Vérification de la taille du build:"
          du -sh ./dist/
          
      # Test de preview du build
      - name: Test build preview
        run: |
          cd blog
          npm run preview &
          sleep 5
          curl -f http://localhost:4173 || echo "⚠️ Preview test failed"
          pkill -f "vite preview" || true